### ISSUE TITLE
Kanban Review

### ISSUE THREAD

**Issue by faizi2500** [faizi2500/recipe-app#12]
[Link to Project](https://github.com/faizi2500/recipe-app/projects/1)

We are a team of 3 and therefore, we included wireframes tasks for inventories. 

@medaminedev66 
@ridaarif98 
@faizi2500

**Comment by descholar-ceo** [comment]
Hi @faizi2500 and @ridaarif98 and @medaminedev66 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue's thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ridaarif98** [comment]
@descholar-ceo  thank you
